# Generated by Django 4.0.6 on 2022-07-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='fragnance',
            field=models.CharField(blank=True, default='', help_text='fragnance of item', max_length=255, verbose_name='fragnance'),
        ),
    ]
