# Generated by Django 4.0.6 on 2022-08-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_comments_user_commentlists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlists',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
